### ISSUE TITLE
./Cuberite: not found

### ISSUE THREAD

**Issue by wesleyyoung** [beevelop/docker-cuberite#4]
Getting `/bin/sh: 1: ./Cuberite: not found` when running stable and nightly images on raspberry pi 4 8gb microk8s Kubernetes.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cuberite-claim0
  name: cuberite-claim0
  namespace: cuberite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cuberite
  name: cuberite
  namespace: cuberite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cuberite
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cuberite
    spec:
      containers:
        - env:
            - name: ADMIN_USERNAME
              value: cuberite
            - name: ADMIN_PASSWORD
              value: admin
          image: beevelop/cuberite:latest
          name: cuberite
          ports:
            - containerPort: 8080
            - containerPort: 25565
          resources: {}
          tty: true
      restartPolicy: Always
      volumes:
        - name: cuberite-claim0
          persistentVolumeClaim:
            claimName: cuberite-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cuberite
  name: cuberite
  namespace: cuberite
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
    - name: "25565"
      port: 25565
      targetPort: 25565
  selector:
    io.kompose.service: cuberite
status:
  loadBalancer: {}

```
